//
//  UIColor+PLNColors.m
//
//  Generated by Zeplin on 12/29/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import "UIColor+PLNColors.h"

@implementation UIColor (PLNColors)

+ (UIColor *)pln_slate60Color {
    return [UIColor colorWithRed:79.0f / 255.0f green:95.0f / 255.0f blue:111.0f / 255.0f alpha:0.6f];
}

+ (UIColor *)pln_slateColor {
    return [UIColor colorWithRed:79.0f / 255.0f green:95.0f / 255.0f blue:111.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_grapefruitColor {
    return [UIColor colorWithRed:255.0f / 255.0f green:82.0f / 255.0f blue:82.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_blueyGreyColor {
    return [UIColor colorWithRed:161.0f / 255.0f green:177.0f / 255.0f blue:194.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_whiteColor {
    return [UIColor colorWithWhite:216.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_blackColor {
    return [UIColor colorWithWhite:0.0f alpha:1.0f];
}

+ (UIColor *)pln_slateGreyColor {
    return [UIColor colorWithRed:95.0f / 255.0f green:100.0f / 255.0f blue:110.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_slateGrey_60A_Color {
    return [UIColor colorWithRed:95.0f / 255.0f green:100.0f / 255.0f blue:110.0f / 255.0f alpha:0.6f];
}

+ (UIColor *)pln_warmGreyColor {
    return [UIColor colorWithWhite:153.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_cloudyBlueColor {
    return [UIColor colorWithRed:215.0f / 255.0f green:221.0f / 255.0f blue:229.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_charcoalGreyColor {
    return [UIColor colorWithRed:61.0f / 255.0f green:66.0f / 255.0f blue:76.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_silverColor {
    return [UIColor colorWithRed:199.0f / 255.0f green:199.0f / 255.0f blue:204.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_darkColor {
    return [UIColor colorWithRed:35.0f / 255.0f green:33.0f / 255.0f blue:44.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_ceruleanColor {
    return [UIColor colorWithRed:0.0f green:116.0f / 255.0f blue:193.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_lightblueColor {
    return [UIColor colorWithRed:122.0f / 255.0f green:199.0f / 255.0f blue:249.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_mediumBlueColor {
    return [UIColor colorWithRed:52.0f / 255.0f green:127.0f / 255.0f blue:209.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_dodgerBlueColor {
    return [UIColor colorWithRed:52.0f / 255.0f green:163.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_coolGreyColor {
    return [UIColor colorWithRed:189.0f / 255.0f green:189.0f / 255.0f blue:191.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_deepSkyBlue80Color {
    return [UIColor colorWithRed:6.0f / 255.0f green:130.0f / 255.0f blue:255.0f / 255.0f alpha:0.8f];
}

+ (UIColor *)pln_deepSkyBlueColor {
    return [UIColor colorWithRed:6.0f / 255.0f green:130.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)pln_purpleyGreyColor {
    return [UIColor colorWithRed:143.0f / 255.0f green:142.0f / 255.0f blue:148.0f / 255.0f alpha:1.0f];
}

@end
