//
//  UIColor+ATColors.m
//
//  Generated by Zeplin on 8/21/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import "UIColor+ATColors.h"


@implementation UIColor (ATColors)

+ (UIColor *)at_deepSkyBlueColor
{
    return [UIColor colorWithRed:6.0f / 255.0f green:130.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)at_clearBlueColor
{
    return [UIColor colorWithRed:27.0f / 255.0f green:130.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)at_charcoalGreyColor
{
    return [UIColor colorWithRed:61.0f / 255.0f green:66.0f / 255.0f blue:76.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)at_blackColor
{
    return [UIColor colorWithWhite:0.0f alpha:1.0f];
}

+ (UIColor *)at_grapefruitColor
{
    return [UIColor colorWithRed:255.0f / 255.0f green:82.0f / 255.0f blue:82.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)at_brownishGreyColor
{
    return [UIColor colorWithWhite:102.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)at_warmGreyColor
{
    return [UIColor colorWithWhite:153.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)at_blueyGreyColor
{
    return [UIColor colorWithRed:161.0f / 255.0f green:177.0f / 255.0f blue:194.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)at_slateGreyColor
{
    return [UIColor colorWithRed:95.0f / 255.0f green:100.0f / 255.0f blue:110.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)at_bluishGreyColor
{
    return [UIColor colorWithRed:126.0f / 255.0f green:142.0f / 255.0f blue:159.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)at_whiteColor
{
    return [UIColor colorWithWhite:248.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)at_slateColor
{
    return [UIColor colorWithRed:79.0f / 255.0f green:95.0f / 255.0f blue:111.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)at_dodgerBlueColor
{
    return [UIColor colorWithRed:56.0f / 255.0f green:155.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}
@end
