//
//  UIColor+ATColors.h
//
//  Generated by Zeplin on 8/21/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import <UIKit/UIKit.h>


@interface UIColor (ATColors)

+ (UIColor *)at_whiteColor;
+ (UIColor *)at_deepSkyBlueColor;
+ (UIColor *)at_clearBlueColor;
+ (UIColor *)at_charcoalGreyColor;
+ (UIColor *)at_blackColor;
+ (UIColor *)at_grapefruitColor;
+ (UIColor *)at_brownishGreyColor;
+ (UIColor *)at_warmGreyColor;
+ (UIColor *)at_blueyGreyColor;
+ (UIColor *)at_slateGreyColor;
+ (UIColor *)at_bluishGreyColor;
+ (UIColor *)at_slateColor;
+ (UIColor *)at_dodgerBlueColor;

@end
